/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package currencyconverter;

import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Cconverter extends javax.swing.JFrame {

    /**
     * Creates new form Cconverter
     */
    public Cconverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextamount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        convert = new javax.swing.JButton();
        txtfrom = new javax.swing.JComboBox<>();
        txtto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Amount");

        jTextamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextamountActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("To");

        convert.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        convert.setText("Convert");
        convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertActionPerformed(evt);
            }
        });

        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dollar", "Indian Rupees", "Euro", "Pound" }));

        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Indian Rupees", "Dollar", "Pound", "Euro" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Currency Converter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextamount)
                                .addComponent(txtfrom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 2, Short.MAX_VALUE))))))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextamount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtto, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addComponent(convert, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextamountActionPerformed

    private void convertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertActionPerformed
        Double convert;
        Double amount = Double.parseDouble(jTextamount.getText());
        
        
        
        
             // Converting rupees to dollars --------------
        if(txtfrom.getSelectedItem().toString()=="Indian Rupees" && txtto.getSelectedItem().toString()=="Dollar"){
            convert = (amount /77.34);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" dollar");
            
            // converting Dollars to rupees ---------------
        }else if(txtfrom.getSelectedItem().toString()=="Dollar" && txtto.getSelectedItem().toString()=="Indian Rupees"){
            convert = (amount  * 77.34);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" Rupees");
            
            // Converting rupees to pound -----------------
        }else if(txtfrom.getSelectedItem().toString()=="Indian Rupees" && txtto.getSelectedItem().toString()=="Pound"){
            convert = (amount  / 94.46);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" pound");
            
             // Converting rupees to euro -------------------
        }else if(txtfrom.getSelectedItem().toString()=="Indian Rupees" && txtto.getSelectedItem().toString()=="Euro"){
            convert = (amount  / 80.36);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" euro");
           
             // Converting dollar to euro 
        }else if(txtfrom.getSelectedItem().toString()=="Dollar" && txtto.getSelectedItem().toString()=="Euro"){
            convert = (amount  * 0.96);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" euro");
            
            // Converting dollar to pound 
        }else if(txtfrom.getSelectedItem().toString()=="Dollar" && txtto.getSelectedItem().toString()=="Pound"){
            convert = (amount  * 0.82);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" pound");
            
            // Converting pound to dollar 
        }else if(txtfrom.getSelectedItem().toString()=="Pound" && txtto.getSelectedItem().toString()=="Dollar"){
            convert = (amount  * 1.22);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" dollar");
        }
        
        //Converting pound to euro 
        
        else if(txtfrom.getSelectedItem().toString()=="Pound" && txtto.getSelectedItem().toString()=="Euro"){
            convert = (amount  * 1.17);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" euro");
        }
           
         //Converting pound to rupees ------------
         else if(txtfrom.getSelectedItem().toString()=="Pound" && txtto.getSelectedItem().toString()=="Indian Rupees"){
            convert = (amount  * 94.43);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" rupees");
        }

         //Converting Euro to rupees -----------------
         else if(txtfrom.getSelectedItem().toString()=="Euro" && txtto.getSelectedItem().toString()=="Indian Rupees"){
            convert = (amount  * 80.43);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" rupees");
        }
        //Converting Euro to dollar -----------------
         else if(txtfrom.getSelectedItem().toString()=="Euro" && txtto.getSelectedItem().toString()=="Dollar"){
            convert = (amount  * 1.04);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" dollar");
        }
           //Converting Euro to pound -----------------
         else if(txtfrom.getSelectedItem().toString()=="Euro" && txtto.getSelectedItem().toString()=="Pound"){
            convert = (amount  * 0.85);
            JOptionPane.showMessageDialog(this, "The Amount is : "+convert.toString()+" pound");
            
            
            //euro to euro
        }else if(txtfrom.getSelectedItem().toString()=="Euro" && txtto.getSelectedItem().toString()=="Euro"){
             JOptionPane.showMessageDialog(this, "The Amount is : "+amount.toString()+" euro");
             
            // pound to pound
        }else if(txtfrom.getSelectedItem().toString()=="Pound" && txtto.getSelectedItem().toString()=="Pound"){
            JOptionPane.showMessageDialog(this, "The Amount is : "+amount.toString()+" pound");
            
            //rupees to rupees
        }else if(txtfrom.getSelectedItem().toString()=="Indian Rupees" && txtto.getSelectedItem().toString()=="Indian Rupees"){
            
            JOptionPane.showMessageDialog(this, "The Amount is : "+amount.toString()+" rupees");
        }else if(txtfrom.getSelectedItem().toString()=="Dollar" && txtto.getSelectedItem().toString()=="Dollar"){
            
            JOptionPane.showMessageDialog(this, "The Amount is : "+amount.toString()+" dollar");
        }
    }//GEN-LAST:event_convertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cconverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cconverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextamount;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JComboBox<String> txtto;
    // End of variables declaration//GEN-END:variables
}
