/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package icecreamshop;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class Shop extends javax.swing.JFrame implements MouseListener{

    /**
     * Creates new form Shop
     */
    public Shop() {
        initComponents();
        
        
        
        cherry.addMouseListener(this);   //for cherry
        pine.addMouseListener(this);     //for pine
        vanila.addMouseListener(this);    //for vanila
        
        
        //pasta
        pasta.addMouseListener(this);
        spicypasta.addMouseListener(this);
        creampasta.addMouseListener(this);
    
    }
    
    
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        vanila = new javax.swing.JLabel();
        cherry = new javax.swing.JLabel();
        pine = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        spicypasta = new javax.swing.JLabel();
        pasta = new javax.swing.JLabel();
        creampasta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtsubtot = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\IcecreamShop\\src\\img\\ice.jpg")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("SHOP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(265, 265, 265))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vanila.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\food\\food_12.png")); // NOI18N

        cherry.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\food\\food_18.png")); // NOI18N

        pine.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\food\\food_20.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cherry, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pine, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vanila, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(vanila, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pine, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cherry, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(452, 452, 452))
        );

        jTabbedPane1.addTab("ICECREAM", jPanel2);

        spicypasta.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\food\\food_26.png")); // NOI18N

        pasta.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\food\\food_25.png")); // NOI18N

        creampasta.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Downloads\\food\\food_27.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(pasta, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spicypasta, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(creampasta, javax.swing.GroupLayout.PREFERRED_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spicypasta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(creampasta, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pasta, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("PASTA", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Qty", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Total :");

        txtsubtot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsubtot, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtsubtot, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cherry;
    private javax.swing.JLabel creampasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel pasta;
    private javax.swing.JLabel pine;
    private javax.swing.JLabel spicypasta;
    private javax.swing.JTextField txtsubtot;
    private javax.swing.JLabel vanila;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
       
        
        
        //cherry
        if(e.getSource()== cherry){
            String name = "Cherry Icecream";
            int price = 45;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
        //pine
        else if(e.getSource()== pine){
            String name = "PineApple Icecream";
            int price = 35;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
        
        //vanila
        else if(e.getSource()== vanila){
            String name = "Vnilla Icecream";
            int price = 45;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
        
        //pasta
            if(e.getSource()== pasta){
            String name = "Plain Pasta";
            int price = 120;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
                if(e.getSource()== cherry){
            String name = "Cherry Icecream";
            int price = 45;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
                
                //Spicy Padta
                else if(e.getSource()== spicypasta){
            String name = "Spicy Pasta";
            int price = 145;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
                
                //Cream pasta
                else if(e.getSource()== creampasta){
            String name = "Cream Pasta";
            int price = 45;
            
            int qty = Integer.parseInt(JOptionPane.showInputDialog("Enter Quantity"));
            int total = price * qty;
            
            
            model = (DefaultTableModel)jTable1.getModel();
            
            model.addRow(new Object[]{
                    
                name,
                price,
                qty,
                total,
               });
            
            
            int sum =0;
            for(int i=0; i<jTable1.getRowCount(); i++){
                
                sum = sum + Integer.parseInt(jTable1.getValueAt(i, 3).toString());
            }
            
            txtsubtot.setText(Integer.toString(sum));
        }
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    @Override
    public void mousePressed(MouseEvent e) {
      
    }

    @Override
    public void mouseReleased(MouseEvent e) {
     
    }

    @Override
    public void mouseEntered(MouseEvent e) {
        
    }

    @Override
    public void mouseExited(MouseEvent e) {
       
    }
}
